apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nosy-narwhal-go 
  janus-idp.io/tekton: nosy-narwhal-go
  backstage.io/kubernetes-id: nosy-narwhal-go
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: nosy-narwhal-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  